name: Gerar Token Mercado Livre

on:
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar requests
        run: pip install requests

      - name: Gerar token
        env:
          ML_CLIENT_ID: ${{ secrets.ML_CLIENT_ID }}
          ML_CLIENT_SECRET: ${{ secrets.ML_CLIENT_SECRET }}
          ML_AUTH_CODE: ${{ secrets.ML_AUTH_CODE }}
        run: python gerar_token.py
