name: Buscador Diecast Automatico

on:
  workflow_dispatch:

  schedule:
    # 08:07 até 11:37 - a cada 30 minutos
    - cron: "7,37 8-11 * * *"
      timezone: "America/Sao_Paulo"

    # 12:07 até 22:52 - a cada 15 minutos
    - cron: "7,22,37,52 12-22 * * *"
      timezone: "America/Sao_Paulo"

    # Última busca do dia às 23:07
    - cron: "7 23 * * *"
      timezone: "America/Sao_Paulo"

permissions:
  contents: write

jobs:
  buscar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v6

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install requests

      - name: Buscar ofertas e enviar email
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}
        run: python main.py

      - name: Salvar historico e links
        run: |
          git config user.name "Buscador Diecast"
          git config user.email "actions@github.com"

          git add ofertas_vistas.json links_para_afiliado.txt

          if git diff --cached --quiet; then
            echo "Nenhuma alteracao para salvar"
          else
            git commit -m "Atualiza ofertas e historico"
            git push
          fi
